### ISSUE TITLE
Error in logging code on assigning grading queue

### ISSUE THREAD

**Issue by msuperdock** [okpy/ok#1415]
I get the following error when trying to assign a grading queue (using the "correctness" option, if it's relevant). The error is that the function `log()` is called with the wrong number of arguments.

Description
    Assign Grading Queues For ...
...
Log

    Job failed
    Traceback (most recent call last):
      File "/code/server/jobs/__init__.py", line 57, in job_handler
        return_value = f(*args, **kwargs)
      File "/code/server/jobs/assign_grading_queues.py", line 26, in assign_grading_queues
        logger.log("{} created!".format(tasks))
    TypeError: log() missing 1 required positional argument: 'msg'

**Comment by msuperdock** [comment]
This was introduced by commit 50a0019 yesterday.

**Comment by rahularya50** [comment]
Sorry about that, will fix. However, the queues themselves should actually be assigned, this error happens after all the changes are committed.

**Comment by rahularya50** [comment]
Should be fixed now. Please reopen if you can still repo
